site_name: 安全运营之路

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
    repo: fontawesome/brands/github
  logo: 'assets/logo_white.png'
  favicon: 'assets/favicon.ico'


extra:
  search:
    language: 'jp'

repo_url: https://github.com/Nan3r/SecurityOps
repo_name: Nan3r/SecurityOps

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets